WITH RECURSIVE 
HOURS AS (
    SELECT 0 AS HOUR
    UNION ALL
    SELECT HOUR + 1
    FROM HOURS
    WHERE HOUR < 23
),
HOUR_COUNT AS (
    SELECT HOUR, COUNT(*) AS COUNT
    FROM (
        SELECT HOUR(DATETIME) AS HOUR
        FROM ANIMAL_OUTS
    ) A
    GROUP BY HOUR
)

SELECT H.HOUR, COALESCE(HC.COUNT, 0)
FROM HOUR_COUNT HC
RIGHT JOIN HOURS H
ON HC.HOUR = H.HOUR

