# SELECT MONTH(B.START_DATE) AS MONTH, A.CAR_ID, COUNT(*) AS RECORDS
# FROM (
#     SELECT CAR_ID, COUNT(CAR_ID) AS TOTAL_RECORDS
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE DATE_FORMAT(START_DATE,'%Y-%m') BETWEEN '2022-08' AND '2022-10'
#     GROUP BY CAR_ID
# ) A
#     JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY B
#     ON A.CAR_ID = B.CAR_ID
# WHERE A.TOTAL_RECORDS>=5
# GROUP BY MONTH, CAR_ID
# ORDER BY MONTH, CAR_ID DESC

SELECT 
    MONTH(START_DATE) AS MONTH,
    CAR_ID, 
    COUNT(*) AS RECORDS
FROM 
    CAR_RENTAL_COMPANY_RENTAL_HISTORY
WHERE
    CAR_ID IN (
        SELECT CAR_ID
        FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
        WHERE MONTH(START_DATE) BETWEEN 8 AND 10
        GROUP BY CAR_ID
        HAVING COUNT(*) >= 5
    )
    AND MONTH(START_DATE) BETWEEN 8 AND 10
GROUP BY 
    MONTH, CAR_ID
ORDER BY 
    MONTH, CAR_ID DESC;
