WITH TRUCKS AS (
    SELECT 
        C.CAR_ID, C.CAR_TYPE, C.DAILY_FEE, H.HISTORY_ID, 
        DATEDIFF(END_DATE, START_DATE) + 1 AS DATES,
        CASE
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 7 THEN NULL
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 30 THEN '7일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 < 90 THEN '30일 이상'
            ELSE '90일 이상'
        END AS DURATION_TYPE
    FROM CAR_RENTAL_COMPANY_CAR C
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY H USING (CAR_ID)
    WHERE C.CAR_TYPE = '트럭'
)

SELECT T.HISTORY_ID, 
    FLOOR((T.DAILY_FEE * T.DATES) * (100 - COALESCE(D.DISCOUNT_RATE, 0)) / 100) AS FEE
FROM TRUCKS T
LEFT JOIN (
    SELECT *
    FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
    WHERE CAR_TYPE = '트럭'
) D
USING(DURATION_TYPE)
ORDER BY FEE DESC, T.HISTORY_ID DESC